#include "zadanie.h"
#include "zespol.h"

extern unsigned short liczba_zadan,
                      liczba_zespolow;
extern zadanie *lista_zadan;
extern zespol *lista_zespolow;

void WczytajMalyPrzyklad()
{
    liczba_zadan = 10,
    liczba_zespolow = 2;  
    
    lista_zadan = new zadanie[liczba_zadan];
    lista_zespolow = new zespol[liczba_zespolow];  
    
    lista_zespolow[0].PodajCechyZespolu("Zespol0", 6);
    lista_zespolow[1].PodajCechyZespolu("Zespol1", 10);
    
    lista_zadan[0].PodajCechyZadania("WP0", 3, 0);
    lista_zadan[1].PodajCechyZadania("WP1", 1, 0);
    lista_zadan[1].DodajPoprzednika(&lista_zadan[0]);
    lista_zadan[2].PodajCechyZadania("WP2", 9, 0);
    lista_zadan[2].DodajPoprzednika(&lista_zadan[0]);
    lista_zadan[3].PodajCechyZadania("WP3", 8, 0);
    lista_zadan[3].DodajPoprzednika(&lista_zadan[2]);
    lista_zadan[3].DodajPoprzednika(&lista_zadan[0]);
    lista_zadan[4].PodajCechyZadania("WP4", 10, 1);
    lista_zadan[5].PodajCechyZadania("WP5", 7, 1);
    lista_zadan[6].PodajCechyZadania("WP6", 7, 0);
    lista_zadan[6].DodajPoprzednika(&lista_zadan[5]);
    lista_zadan[7].PodajCechyZadania("WP7", 10, 0);
    lista_zadan[7].DodajPoprzednika(&lista_zadan[1]);
    lista_zadan[7].DodajPoprzednika(&lista_zadan[0]);
    lista_zadan[8].PodajCechyZadania("WP8", 9, 1);
    lista_zadan[8].DodajPoprzednika(&lista_zadan[6]);
    lista_zadan[8].DodajPoprzednika(&lista_zadan[5]);
    lista_zadan[9].PodajCechyZadania("WP9", 9, 1);
    lista_zadan[9].DodajPoprzednika(&lista_zadan[7]);
    lista_zadan[9].DodajPoprzednika(&lista_zadan[1]);
    lista_zadan[9].DodajPoprzednika(&lista_zadan[0]);
}
//------------------------------------------------------------------------------
void WczytajDuzyPrzyklad()
{
    liczba_zadan = 50,
    liczba_zespolow = 5;  
    
    lista_zadan = new zadanie[liczba_zadan];
    lista_zespolow = new zespol[liczba_zespolow];  
    
    lista_zespolow[0].PodajCechyZespolu("Zespol0", 2);
    lista_zespolow[1].PodajCechyZespolu("Zespol1", 6);
    lista_zespolow[2].PodajCechyZespolu("Zespol2", 2);
    lista_zespolow[3].PodajCechyZespolu("Zespol3", 10);
    lista_zespolow[4].PodajCechyZespolu("Zespol4", 9);
    
    lista_zadan[0].PodajCechyZadania("WP0", 10, 1);
    lista_zadan[1].PodajCechyZadania("WP1", 7, 2);
    lista_zadan[1].DodajPoprzednika(&lista_zadan[0]);
    lista_zadan[2].PodajCechyZadania("WP2", 9, 3);
    lista_zadan[2].DodajPoprzednika(&lista_zadan[0]);
    lista_zadan[3].PodajCechyZadania("WP3", 6, 1);
    lista_zadan[3].DodajPoprzednika(&lista_zadan[0]);
    lista_zadan[4].PodajCechyZadania("WP4", 4, 0);
    lista_zadan[4].DodajPoprzednika(&lista_zadan[3]);
    lista_zadan[4].DodajPoprzednika(&lista_zadan[0]);
    lista_zadan[5].PodajCechyZadania("WP5", 2, 3);
    lista_zadan[5].DodajPoprzednika(&lista_zadan[4]);
    lista_zadan[5].DodajPoprzednika(&lista_zadan[3]);
    lista_zadan[5].DodajPoprzednika(&lista_zadan[0]);
    lista_zadan[6].PodajCechyZadania("WP6", 5, 2);
    lista_zadan[6].DodajPoprzednika(&lista_zadan[5]);
    lista_zadan[6].DodajPoprzednika(&lista_zadan[4]);
    lista_zadan[6].DodajPoprzednika(&lista_zadan[3]);
    lista_zadan[6].DodajPoprzednika(&lista_zadan[0]);
    lista_zadan[7].PodajCechyZadania("WP7", 5, 3);
    lista_zadan[7].DodajPoprzednika(&lista_zadan[6]);
    lista_zadan[7].DodajPoprzednika(&lista_zadan[5]);
    lista_zadan[7].DodajPoprzednika(&lista_zadan[4]);
    lista_zadan[7].DodajPoprzednika(&lista_zadan[3]);
    lista_zadan[7].DodajPoprzednika(&lista_zadan[0]);
    lista_zadan[8].PodajCechyZadania("WP8", 2, 2);
    lista_zadan[8].DodajPoprzednika(&lista_zadan[4]);
    lista_zadan[8].DodajPoprzednika(&lista_zadan[3]);
    lista_zadan[8].DodajPoprzednika(&lista_zadan[0]);
    lista_zadan[9].PodajCechyZadania("WP9", 9, 3);
    lista_zadan[9].DodajPoprzednika(&lista_zadan[1]);
    lista_zadan[9].DodajPoprzednika(&lista_zadan[0]);
    lista_zadan[10].PodajCechyZadania("WP10", 4, 2);
    lista_zadan[10].DodajPoprzednika(&lista_zadan[5]);
    lista_zadan[10].DodajPoprzednika(&lista_zadan[4]);
    lista_zadan[10].DodajPoprzednika(&lista_zadan[3]);
    lista_zadan[10].DodajPoprzednika(&lista_zadan[0]);
    lista_zadan[11].PodajCechyZadania("WP11", 5, 1);
    lista_zadan[11].DodajPoprzednika(&lista_zadan[9]);
    lista_zadan[11].DodajPoprzednika(&lista_zadan[1]);
    lista_zadan[11].DodajPoprzednika(&lista_zadan[0]);
    lista_zadan[12].PodajCechyZadania("WP12", 10, 2);
    lista_zadan[12].DodajPoprzednika(&lista_zadan[10]);
    lista_zadan[12].DodajPoprzednika(&lista_zadan[5]);
    lista_zadan[12].DodajPoprzednika(&lista_zadan[4]);
    lista_zadan[12].DodajPoprzednika(&lista_zadan[3]);
    lista_zadan[12].DodajPoprzednika(&lista_zadan[0]);
    lista_zadan[13].PodajCechyZadania("WP13", 1, 4);
    lista_zadan[13].DodajPoprzednika(&lista_zadan[5]);
    lista_zadan[13].DodajPoprzednika(&lista_zadan[4]);
    lista_zadan[13].DodajPoprzednika(&lista_zadan[3]);
    lista_zadan[13].DodajPoprzednika(&lista_zadan[0]);
    lista_zadan[14].PodajCechyZadania("WP14", 10, 1);
    lista_zadan[14].DodajPoprzednika(&lista_zadan[7]);
    lista_zadan[14].DodajPoprzednika(&lista_zadan[6]);
    lista_zadan[14].DodajPoprzednika(&lista_zadan[5]);
    lista_zadan[14].DodajPoprzednika(&lista_zadan[4]);
    lista_zadan[14].DodajPoprzednika(&lista_zadan[3]);
    lista_zadan[14].DodajPoprzednika(&lista_zadan[0]);
    lista_zadan[15].PodajCechyZadania("WP15", 7, 1);
    lista_zadan[15].DodajPoprzednika(&lista_zadan[1]);
    lista_zadan[15].DodajPoprzednika(&lista_zadan[0]);
    lista_zadan[16].PodajCechyZadania("WP16", 3, 1);
    lista_zadan[16].DodajPoprzednika(&lista_zadan[10]);
    lista_zadan[16].DodajPoprzednika(&lista_zadan[5]);
    lista_zadan[16].DodajPoprzednika(&lista_zadan[4]);
    lista_zadan[16].DodajPoprzednika(&lista_zadan[3]);
    lista_zadan[16].DodajPoprzednika(&lista_zadan[0]);
    lista_zadan[17].PodajCechyZadania("WP17", 8, 4);
    lista_zadan[17].DodajPoprzednika(&lista_zadan[3]);
    lista_zadan[17].DodajPoprzednika(&lista_zadan[0]);
    lista_zadan[18].PodajCechyZadania("WP18", 1, 3);
    lista_zadan[18].DodajPoprzednika(&lista_zadan[4]);
    lista_zadan[18].DodajPoprzednika(&lista_zadan[3]);
    lista_zadan[18].DodajPoprzednika(&lista_zadan[0]);
    lista_zadan[19].PodajCechyZadania("WP19", 10, 3);
    lista_zadan[19].DodajPoprzednika(&lista_zadan[0]);
    lista_zadan[20].PodajCechyZadania("WP20", 4, 0);
    lista_zadan[20].DodajPoprzednika(&lista_zadan[5]);
    lista_zadan[20].DodajPoprzednika(&lista_zadan[4]);
    lista_zadan[20].DodajPoprzednika(&lista_zadan[3]);
    lista_zadan[20].DodajPoprzednika(&lista_zadan[0]);
    lista_zadan[21].PodajCechyZadania("WP21", 9, 1);
    lista_zadan[21].DodajPoprzednika(&lista_zadan[4]);
    lista_zadan[21].DodajPoprzednika(&lista_zadan[3]);
    lista_zadan[21].DodajPoprzednika(&lista_zadan[0]);
    lista_zadan[22].PodajCechyZadania("WP22", 8, 2);
    lista_zadan[22].DodajPoprzednika(&lista_zadan[15]);
    lista_zadan[22].DodajPoprzednika(&lista_zadan[1]);
    lista_zadan[22].DodajPoprzednika(&lista_zadan[0]);
    lista_zadan[23].PodajCechyZadania("WP23", 7, 4);
    lista_zadan[23].DodajPoprzednika(&lista_zadan[7]);
    lista_zadan[23].DodajPoprzednika(&lista_zadan[6]);
    lista_zadan[23].DodajPoprzednika(&lista_zadan[5]);
    lista_zadan[23].DodajPoprzednika(&lista_zadan[4]);
    lista_zadan[23].DodajPoprzednika(&lista_zadan[3]);
    lista_zadan[23].DodajPoprzednika(&lista_zadan[0]);
    lista_zadan[24].PodajCechyZadania("WP24", 1, 1);
    lista_zadan[24].DodajPoprzednika(&lista_zadan[11]);
    lista_zadan[24].DodajPoprzednika(&lista_zadan[9]);
    lista_zadan[24].DodajPoprzednika(&lista_zadan[1]);
    lista_zadan[24].DodajPoprzednika(&lista_zadan[0]);
    lista_zadan[25].PodajCechyZadania("WP25", 6, 3);
    lista_zadan[25].DodajPoprzednika(&lista_zadan[23]);
    lista_zadan[25].DodajPoprzednika(&lista_zadan[7]);
    lista_zadan[25].DodajPoprzednika(&lista_zadan[6]);
    lista_zadan[25].DodajPoprzednika(&lista_zadan[5]);
    lista_zadan[25].DodajPoprzednika(&lista_zadan[4]);
    lista_zadan[25].DodajPoprzednika(&lista_zadan[3]);
    lista_zadan[25].DodajPoprzednika(&lista_zadan[0]);
    lista_zadan[26].PodajCechyZadania("WP26", 4, 1);
    lista_zadan[26].DodajPoprzednika(&lista_zadan[17]);
    lista_zadan[26].DodajPoprzednika(&lista_zadan[3]);
    lista_zadan[26].DodajPoprzednika(&lista_zadan[0]);
    lista_zadan[27].PodajCechyZadania("WP27", 9, 4);
    lista_zadan[27].DodajPoprzednika(&lista_zadan[5]);
    lista_zadan[27].DodajPoprzednika(&lista_zadan[4]);
    lista_zadan[27].DodajPoprzednika(&lista_zadan[3]);
    lista_zadan[27].DodajPoprzednika(&lista_zadan[0]);
    lista_zadan[28].PodajCechyZadania("WP28", 8, 2);
    lista_zadan[28].DodajPoprzednika(&lista_zadan[10]);
    lista_zadan[28].DodajPoprzednika(&lista_zadan[5]);
    lista_zadan[28].DodajPoprzednika(&lista_zadan[4]);
    lista_zadan[28].DodajPoprzednika(&lista_zadan[3]);
    lista_zadan[28].DodajPoprzednika(&lista_zadan[0]);
    lista_zadan[29].PodajCechyZadania("WP29", 4, 4);
    lista_zadan[29].DodajPoprzednika(&lista_zadan[27]);
    lista_zadan[29].DodajPoprzednika(&lista_zadan[5]);
    lista_zadan[29].DodajPoprzednika(&lista_zadan[4]);
    lista_zadan[29].DodajPoprzednika(&lista_zadan[3]);
    lista_zadan[29].DodajPoprzednika(&lista_zadan[0]);
    lista_zadan[30].PodajCechyZadania("WP30", 7, 3);
    lista_zadan[30].DodajPoprzednika(&lista_zadan[24]);
    lista_zadan[30].DodajPoprzednika(&lista_zadan[11]);
    lista_zadan[30].DodajPoprzednika(&lista_zadan[9]);
    lista_zadan[30].DodajPoprzednika(&lista_zadan[1]);
    lista_zadan[30].DodajPoprzednika(&lista_zadan[0]);
    lista_zadan[31].PodajCechyZadania("WP31", 9, 3);
    lista_zadan[31].DodajPoprzednika(&lista_zadan[8]);
    lista_zadan[31].DodajPoprzednika(&lista_zadan[4]);
    lista_zadan[31].DodajPoprzednika(&lista_zadan[3]);
    lista_zadan[31].DodajPoprzednika(&lista_zadan[0]);
    lista_zadan[32].PodajCechyZadania("WP32", 8, 2);
    lista_zadan[32].DodajPoprzednika(&lista_zadan[15]);
    lista_zadan[32].DodajPoprzednika(&lista_zadan[1]);
    lista_zadan[32].DodajPoprzednika(&lista_zadan[0]);
    lista_zadan[33].PodajCechyZadania("WP33", 5, 3);
    lista_zadan[33].DodajPoprzednika(&lista_zadan[32]);
    lista_zadan[33].DodajPoprzednika(&lista_zadan[15]);
    lista_zadan[33].DodajPoprzednika(&lista_zadan[1]);
    lista_zadan[33].DodajPoprzednika(&lista_zadan[0]);
    lista_zadan[34].PodajCechyZadania("WP34", 7, 4);
    lista_zadan[34].DodajPoprzednika(&lista_zadan[24]);
    lista_zadan[34].DodajPoprzednika(&lista_zadan[11]);
    lista_zadan[34].DodajPoprzednika(&lista_zadan[9]);
    lista_zadan[34].DodajPoprzednika(&lista_zadan[1]);
    lista_zadan[34].DodajPoprzednika(&lista_zadan[0]);
    lista_zadan[35].PodajCechyZadania("WP35", 5, 2);
    lista_zadan[35].DodajPoprzednika(&lista_zadan[5]);
    lista_zadan[35].DodajPoprzednika(&lista_zadan[4]);
    lista_zadan[35].DodajPoprzednika(&lista_zadan[3]);
    lista_zadan[35].DodajPoprzednika(&lista_zadan[0]);
    lista_zadan[36].PodajCechyZadania("WP36", 6, 4);
    lista_zadan[36].DodajPoprzednika(&lista_zadan[7]);
    lista_zadan[36].DodajPoprzednika(&lista_zadan[6]);
    lista_zadan[36].DodajPoprzednika(&lista_zadan[5]);
    lista_zadan[36].DodajPoprzednika(&lista_zadan[4]);
    lista_zadan[36].DodajPoprzednika(&lista_zadan[3]);
    lista_zadan[36].DodajPoprzednika(&lista_zadan[0]);
    lista_zadan[37].PodajCechyZadania("WP37", 6, 4);
    lista_zadan[37].DodajPoprzednika(&lista_zadan[0]);
    lista_zadan[38].PodajCechyZadania("WP38", 8, 3);
    lista_zadan[38].DodajPoprzednika(&lista_zadan[28]);
    lista_zadan[38].DodajPoprzednika(&lista_zadan[10]);
    lista_zadan[38].DodajPoprzednika(&lista_zadan[5]);
    lista_zadan[38].DodajPoprzednika(&lista_zadan[4]);
    lista_zadan[38].DodajPoprzednika(&lista_zadan[3]);
    lista_zadan[38].DodajPoprzednika(&lista_zadan[0]);
    lista_zadan[39].PodajCechyZadania("WP39", 8, 1);
    lista_zadan[39].DodajPoprzednika(&lista_zadan[23]);
    lista_zadan[39].DodajPoprzednika(&lista_zadan[7]);
    lista_zadan[39].DodajPoprzednika(&lista_zadan[6]);
    lista_zadan[39].DodajPoprzednika(&lista_zadan[5]);
    lista_zadan[39].DodajPoprzednika(&lista_zadan[4]);
    lista_zadan[39].DodajPoprzednika(&lista_zadan[3]);
    lista_zadan[39].DodajPoprzednika(&lista_zadan[0]);
    lista_zadan[40].PodajCechyZadania("WP40", 4, 3);
    lista_zadan[40].DodajPoprzednika(&lista_zadan[39]);
    lista_zadan[40].DodajPoprzednika(&lista_zadan[23]);
    lista_zadan[40].DodajPoprzednika(&lista_zadan[7]);
    lista_zadan[40].DodajPoprzednika(&lista_zadan[6]);
    lista_zadan[40].DodajPoprzednika(&lista_zadan[5]);
    lista_zadan[40].DodajPoprzednika(&lista_zadan[4]);
    lista_zadan[40].DodajPoprzednika(&lista_zadan[3]);
    lista_zadan[40].DodajPoprzednika(&lista_zadan[0]);
    lista_zadan[41].PodajCechyZadania("WP41", 7, 2);
    lista_zadan[41].DodajPoprzednika(&lista_zadan[37]);
    lista_zadan[41].DodajPoprzednika(&lista_zadan[0]);
    lista_zadan[42].PodajCechyZadania("WP42", 4, 2);
    lista_zadan[42].DodajPoprzednika(&lista_zadan[28]);
    lista_zadan[42].DodajPoprzednika(&lista_zadan[10]);
    lista_zadan[42].DodajPoprzednika(&lista_zadan[5]);
    lista_zadan[42].DodajPoprzednika(&lista_zadan[4]);
    lista_zadan[42].DodajPoprzednika(&lista_zadan[3]);
    lista_zadan[42].DodajPoprzednika(&lista_zadan[0]);
    lista_zadan[43].PodajCechyZadania("WP43", 6, 0);
    lista_zadan[43].DodajPoprzednika(&lista_zadan[15]);
    lista_zadan[43].DodajPoprzednika(&lista_zadan[1]);
    lista_zadan[43].DodajPoprzednika(&lista_zadan[0]);
    lista_zadan[44].PodajCechyZadania("WP44", 10, 0);
    lista_zadan[44].DodajPoprzednika(&lista_zadan[32]);
    lista_zadan[44].DodajPoprzednika(&lista_zadan[15]);
    lista_zadan[44].DodajPoprzednika(&lista_zadan[1]);
    lista_zadan[44].DodajPoprzednika(&lista_zadan[0]);
    lista_zadan[45].PodajCechyZadania("WP45", 9, 4);
    lista_zadan[45].DodajPoprzednika(&lista_zadan[39]);
    lista_zadan[45].DodajPoprzednika(&lista_zadan[23]);
    lista_zadan[45].DodajPoprzednika(&lista_zadan[7]);
    lista_zadan[45].DodajPoprzednika(&lista_zadan[6]);
    lista_zadan[45].DodajPoprzednika(&lista_zadan[5]);
    lista_zadan[45].DodajPoprzednika(&lista_zadan[4]);
    lista_zadan[45].DodajPoprzednika(&lista_zadan[3]);
    lista_zadan[45].DodajPoprzednika(&lista_zadan[0]);
    lista_zadan[46].PodajCechyZadania("WP46", 7, 1);
    lista_zadan[46].DodajPoprzednika(&lista_zadan[25]);
    lista_zadan[46].DodajPoprzednika(&lista_zadan[23]);
    lista_zadan[46].DodajPoprzednika(&lista_zadan[7]);
    lista_zadan[46].DodajPoprzednika(&lista_zadan[6]);
    lista_zadan[46].DodajPoprzednika(&lista_zadan[5]);
    lista_zadan[46].DodajPoprzednika(&lista_zadan[4]);
    lista_zadan[46].DodajPoprzednika(&lista_zadan[3]);
    lista_zadan[46].DodajPoprzednika(&lista_zadan[0]);
    lista_zadan[47].PodajCechyZadania("WP47", 6, 2);
    lista_zadan[47].DodajPoprzednika(&lista_zadan[46]);
    lista_zadan[47].DodajPoprzednika(&lista_zadan[25]);
    lista_zadan[47].DodajPoprzednika(&lista_zadan[23]);
    lista_zadan[47].DodajPoprzednika(&lista_zadan[7]);
    lista_zadan[47].DodajPoprzednika(&lista_zadan[6]);
    lista_zadan[47].DodajPoprzednika(&lista_zadan[5]);
    lista_zadan[47].DodajPoprzednika(&lista_zadan[4]);
    lista_zadan[47].DodajPoprzednika(&lista_zadan[3]);
    lista_zadan[47].DodajPoprzednika(&lista_zadan[0]);
    lista_zadan[48].PodajCechyZadania("WP48", 1, 1);
    lista_zadan[48].DodajPoprzednika(&lista_zadan[18]);
    lista_zadan[48].DodajPoprzednika(&lista_zadan[4]);
    lista_zadan[48].DodajPoprzednika(&lista_zadan[3]);
    lista_zadan[48].DodajPoprzednika(&lista_zadan[0]);
    lista_zadan[49].PodajCechyZadania("WP49", 10, 3);
    lista_zadan[49].DodajPoprzednika(&lista_zadan[35]);
    lista_zadan[49].DodajPoprzednika(&lista_zadan[5]);
    lista_zadan[49].DodajPoprzednika(&lista_zadan[4]);
    lista_zadan[49].DodajPoprzednika(&lista_zadan[3]);
    lista_zadan[49].DodajPoprzednika(&lista_zadan[0]);
}
